name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@master
      with:
        ruby-version: '2.7'
    - name: Setup
      run: bundle install
    - name: Build
      run: JEKYLL_ENV=production bundle exec jekyll build 
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: _site
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: build
        path: _site
    - name: Debug
      run: |
        ls -lah
        echo "====="
        ls -lah _site
    - name: Deploy
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avn --delete
        RSYNC_TARGET: /mnt/me-kerjean-pages/projects/filestash/website/
        RSYNC_SOURCE: _site/
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_USERNAME: ${{secrets.SSH_USERNAME}}
        SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
